name: ssp_mexico_nm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib=3.9.2
  - xlsxwriter=3.1.1
  - ipykernel=6.29.5
  - pip
  - pip:
      - git+https://github.com/jcsyme/sisepuede.git
      - ssp-transformations-handler==0.1.8
      - costs-benefits-ssp
      - polars
